### ISSUE TITLE
profiles/arch/mips/use.mask/global-mask-reverts need some upgrade

### ISSUE THREAD

**Issue by xmzgtx** [xen0n/loongson-overlay#33]
Failed to use vaapi due to rencently change of official profiles/arch/mips/use.mask:vaapi has been masked.

**Comment by xen0n** [comment]
Hi, try updating and tell me if it's working? I can't test on mips right now, my Loongson 3A4000 box hasn't been powered on for a while and is (again) severely outdated.

**Comment by xmzgtx** [comment]
It works now,thanks!

**Comment by xen0n** [comment]
Thanks for the quick feedback! Glad that helped.
